name: 'FOSSA'

on:
  - pull_request
  - push

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Install Dependencies"
        run: |
          yarn --frozen-lockfile || true

      - name: "Run some shell commands"
        run: |
          ls
          ls -la .git
          git remote -v

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{secrets.fossaApiKey}}

      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{secrets.fossaApiKey}}
          run-tests: true
